package main

import "regexp"

// GameConfig holds all game constants.
var GameConfig = struct {
	TickRate        int
	MaxPlayers      int
	MinPlayers      int
	QueueCountdown  int
	ReadyCountdown  int
	PlayerHP        int
	LMSPlayerHP     int
	PlayerSpeed     float64
	PlayerRadius    float64
	ShotsPerMag     int
	ShotCooldown    int64 // ms
	ReloadTime      int64
	MachinegunReloadTime int64
	ShotgunReloadTime    int64
	SniperReloadTime     int64
	BulletSpeed     float64
	BulletLifetime  int64
	ArenaWidth      float64
	ArenaHeight     float64
	// Machinegun
	MachinegunCooldown int64
	MachinegunDamage   int
	MachinegunRecoil   float64
	// Shotgun
	ShotgunCooldown int64
	ShotgunDamage   int
	ShotgunPellets  int
	ShotgunSpread   float64
	ShotgunAmmo     int
	ShotgunBulletLifetime int64
	ShotgunBulletSpeed float64
	// Knife
	KnifeCooldown   int64
	KnifeDamage     int
	KnifeRange      float64
	KnifeSpeedBonus float64
	// Pickups
	PickupSpawnInterval  int64
	PickupLifetime       int64
	PickupRadius         float64
	PickupHealthAmount   int
	PickupSpeedDuration  int64
	PickupSpeedMultiplier float64
	MaxPickups           int
	// Minigun
	MinigunCooldown int64
	MinigunDamage   int
	MinigunRecoil   float64
	MinigunDuration int64
	// Sniper
	SniperCooldown    int64
	SniperDamage      int
	SniperBulletSpeed float64
	SniperAmmo        int
	// Shield
	ShieldDuration int64
	ShieldAbsorb   int
	// Invisibility
	InvisibilityDuration int64
	// Regen
	RegenDuration     int64
	RegenTickInterval int64
	// Armor
	ArmorAmount int
	ArmorMax    int
	// Dash
	DashCooldown   int64
	DashDuration   int64
	DashSpeed      float64
	DashInvincible bool
	// Bombs
	BombSpawnInterval int64
	BombFuseTime      int64
	BombDamage        int
	BombRadius        float64
	// Lightning
	LightningSpawnInterval int64
	LightningFuseTime      int64
	LightningDamage        int
	LightningRadius        float64
	LightningBlindDuration int64
	// Score
	KillsToWin    int
	GameDuration  int64
	RoundDuration int64
	RoundRestartDelay int64
	KillScore     int
	OrbScore      int
	// Orbs
	OrbSpawnInterval     int64
	OrbRadius            float64
	OrbMax               int
	OrbLifetime          int64
	DeathOrbDropFraction float64
	// Respawn
	RespawnTime int64
	// Obstacle spawn
	ObstacleSpawnInterval int64
	// Zone shrink (disabled)
	ZoneShrinkStart    int64
	ZoneShrinkInterval int64
	ZoneShrinkRate     float64
	ZoneDamageInterval int64
	ZoneDamage         int
	ZoneMinSize        float64
	// Loot crates
	LootCrateHP             int
	LootCrateSize           float64
	LootCrateCount          int
	LootCrateRespawnInterval int64
	LootCrateMax            int
	// Room
	RoomMaxPlayers   int
	RoomReadyTimeout int
	PreGameReadyTimeout int
	// Username
	UsernameMinLen int
	UsernameMaxLen int
	UsernamePattern *regexp.Regexp
}{
	TickRate:        35,
	MaxPlayers:      10,
	MinPlayers:      2,
	QueueCountdown:  10,
	ReadyCountdown:  3,
	PlayerHP:        8,
	LMSPlayerHP:     20,
	PlayerSpeed:     9,
	PlayerRadius:    20,
	ShotsPerMag:     45,
	ShotCooldown:    40,
	ReloadTime:      1950,
	MachinegunReloadTime: 1800,
	ShotgunReloadTime:    2200,
	SniperReloadTime:     2800,
	BulletSpeed:     22,
	BulletLifetime:  2500,
	ArenaWidth:      4000,
	ArenaHeight:     4000,
	// Machinegun
	MachinegunCooldown: 40,
	MachinegunDamage:   1,
	MachinegunRecoil:   0.10,
	// Shotgun
	ShotgunCooldown: 450,
	ShotgunDamage:   4,
	ShotgunPellets:  8,
	ShotgunSpread:   0.40,
	ShotgunAmmo:     10,
	ShotgunBulletLifetime: 700,
	ShotgunBulletSpeed: 0.65,
	// Knife
	KnifeCooldown:   180,
	KnifeDamage:     5,
	KnifeRange:      70,
	KnifeSpeedBonus: 1.6,
	// Pickups
	PickupSpawnInterval:  18000,
	PickupLifetime:       30000,
	PickupRadius:         40,
	PickupHealthAmount:   5,
	PickupSpeedDuration:  12000,
	PickupSpeedMultiplier: 1.5,
	MaxPickups:           4,
	// Minigun
	MinigunCooldown: 14,
	MinigunDamage:   2,
	MinigunRecoil:   0.06,
	MinigunDuration: 15000,
	// Sniper
	SniperCooldown:    900,
	SniperDamage:      10,
	SniperBulletSpeed: 48,
	SniperAmmo:        10,
	// Shield
	ShieldDuration: 15000,
	ShieldAbsorb:   5,
	// Invisibility
	InvisibilityDuration: 12000,
	// Regen
	RegenDuration:     16000,
	RegenTickInterval: 1200,
	// Armor
	ArmorAmount: 3,
	ArmorMax:    3,
	// Dash
	DashCooldown:   1000,
	DashDuration:   150,
	DashSpeed:      42,
	DashInvincible: true,
	// Bombs
	BombSpawnInterval: 3000,
	BombFuseTime:      1000,
	BombDamage:        1,
	BombRadius:        80,
	// Lightning
	LightningSpawnInterval: 5000,
	LightningFuseTime:      250,
	LightningDamage:        2,
	LightningRadius:        150,
	LightningBlindDuration: 5000,
	// Score
	KillsToWin:    999,
	GameDuration:  0,
	RoundDuration: 300000,
	RoundRestartDelay: 10000,
	KillScore:     10,
	OrbScore:      1,
	// Orbs
	OrbSpawnInterval:     1500,
	OrbRadius:            16,
	OrbMax:               250,
	OrbLifetime:          45000,
	DeathOrbDropFraction: 0.5,
	// Respawn
	RespawnTime: 2000,
	// Obstacle spawn
	ObstacleSpawnInterval: 8000,
	// Zone (disabled)
	ZoneShrinkStart:    999999999,
	ZoneShrinkInterval: 100,
	ZoneShrinkRate:     0.3,
	ZoneDamageInterval: 1000,
	ZoneDamage:         1,
	ZoneMinSize:        200,
	// Loot crates
	LootCrateHP:             3,
	LootCrateSize:           28,
	LootCrateCount:          6,
	LootCrateRespawnInterval: 20000,
	LootCrateMax:            8,
	// Room
	RoomMaxPlayers:   10,
	RoomReadyTimeout: 45,
	PreGameReadyTimeout: 15,
	// Username
	UsernameMinLen: 2,
	UsernameMaxLen: 16,
	UsernamePattern: regexp.MustCompile(`^[a-zA-Z0-9_]+$`),
}

// WeaponCycle is the order of weapons when cycling.
var WeaponCycle = []WeaponType{WeaponMachinegun, WeaponShotgun, WeaponSniper}

// ObstacleConfig holds obstacle generation parameters.
var ObstacleConfig = struct {
	WallCountMin  int
	WallCountMax  int
	WallLengthMin int
	WallLengthMax int
	WallBlockSize float64
	WallSpacing   float64
	TreeCountMin  int
	TreeCountMax  int
	TreeSize      float64
	TreeSpacing   float64
}{
	WallCountMin:  40,
	WallCountMax:  60,
	WallLengthMin: 2,
	WallLengthMax: 10,
	WallBlockSize: 14,
	WallSpacing:   60,
	TreeCountMin:  20,
	TreeCountMax:  35,
	TreeSize:      24,
	TreeSpacing:   70,
}
